
stages:
  - build-and-push

variables:
  
  IMAGE_REGISTRY: "registry.gitlab.com/devops2255146/flexidesk-project"
  
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA


before_script:
  - echo "Logging in to GitLab Container Registry..."
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build-service-ressources:
  stage: build-and-push
  
  image: docker:24-git
  services:
    - docker:24-dind
  script:
    - echo "Building service-ressources..."
   
    - docker build -t $IMAGE_REGISTRY/service-ressources:$IMAGE_TAG -f service-ressources/Dockerfile .
    
    - docker push $IMAGE_REGISTRY/service-ressources:$IMAGE_TAG


build-service-utilisateurs:
  stage: build-and-push
  image: docker:24-git
  services:
    - docker:24-dind
  script:
    - echo "Building service-utilisateurs..."
    - docker build -t $IMAGE_REGISTRY/service-utilisateurs:$IMAGE_TAG -f service-utilisateurs/Dockerfile .
    - docker push $IMAGE_REGISTRY/service-utilisateurs:$IMAGE_TAG

# --- Tâche 3 : Build Service-Reservations ---
build-service-reservations:
  stage: build-and-push
  image: docker:24-git
  services:
    - docker:24-dind
  script:
    - echo "Building service-reservations..."
    - docker build -t $IMAGE_REGISTRY/service-reservations:$IMAGE_TAG -f service-reservations/Dockerfile .
    - docker push $IMAGE_REGISTRY/service-reservations:$IMAGE_TAG

# --- Tâche 4 : Build API-Gateway ---
build-api-gateway:
  stage: build-and-push
  image: docker:24-git
  services:
    - docker:24-dind
  script:
    - echo "Building api-gateway..."
    - docker build -t $IMAGE_REGISTRY/api-gateway:$IMAGE_TAG -f api-gateway/Dockerfile .
    - docker push $IMAGE_REGISTRY/api-gateway:$IMAGE_TAG

build-frontend-react:
  stage: build-and-push
  image: docker:24-git
  services:
    - docker:24-dind
  script:
    - echo "Building frontend-react..."
    - docker build -t $IMAGE_REGISTRY/frontend-react:$IMAGE_TAG -f frontend-react/Dockerfile .
    - docker push $IMAGE_REGISTRY/frontend-react:$IMAGE_TAG