

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flexidesk-ingress
spec:
  rules:
  - host: 13.51.121.181.nip.io  # Astuce magique pour un "faux" domaine
    http:
      paths:
      # Règle 1: Tout ce qui commence par /api/v1... va à la gateway
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
      # Règle 2: Tout le reste (/) va au frontend React
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-react
            port:
              number: 80