apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flexidesk-ingress
  annotations:
    # Dit à K8s d'utiliser notre 'ClusterIssuer'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Dit à Traefik de forcer la redirection HTTPS
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "default-redirect-https@kubernetescrd"
spec:
  tls:
  - hosts:
    - ailyes.com
    - www.ailyes.com
    secretName: ailyes-com-tls
  
  rules:
  # Règle pour ailyes.com
  - host: ailyes.com
    http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-react
            port:
              number: 80
              
  # Règle pour www.ailyes.com (dupliquée manuellement)
  - host: www.ailyes.com
    http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-react
            port:
              number: 80